### PR TITLE
Fix the segfault when generate_xml is set to yes.

### PR DESCRIPTION
**Pull request by maxGimeno**
This PR fixes the segfault that occurs when one tries to generate XML for a CGAL package.

### CODE REVIEW

**Review by lrineau — APPROVED** [review]

**Comment by sloriot** [comment]
@maxGimeno this patch should also go upstream.

**Comment by maxGimeno** [comment]
@sloriot what do you mean ? The other branchs don't need that patch.

**Comment by sloriot** [comment]
I mean https://github.com/doxygen/doxygen

**Comment by maxGimeno** [comment]
Same thing, they don't have any unsecured call to `al`.

**Comment by sloriot** [comment]
Original fix is:
https://github.com/doxygen/doxygen/commit/0f02761a158a5e9ddbd5801682482af8986dbc35

**Pull request merged**
